### ISSUE TITLE
Option to skip computation of the total mosaic in batmosaic_analysis

### ISSUE THREAD

**Issue by Parrazyte** [parsotat/BatAnalysis#22]
Currently, `batmosaic_analysis` always computes all the time-bins mosaics AND the total mosaic resulting from the combination of all of them.

Depending on the objective, this may not always be useful, and takes a lot of computing time/space. 

Would adding a simple new argument (to ask whether computing the final mosaic is necessary) clash with other parts of the code ?

**Comment by parsotat** [comment]
Hi @Parrazyte, thanks for the suggestion. Adding this is a good idea and should not break the code in other parts. The functions that are located in the parallel.py file are very general and you can easily copy that function, remove the part where the total mosaic is calculated, and use that new function as your own customized `batmosaic_analysis` function.  

This is a temporary fix since I am expecting the survey code to have a major refactoring once the TTE analysis is ready for publication.

**Comment by Parrazyte** [comment]
Indeed, I changed that on my fork. I'll be waiting for the next version then :)

**Comment by parsotat** [comment]
This was addressed via PR #26
